### ISSUE TITLE
How to parse value automatically?

### ISSUE THREAD

**Issue by phlegx** [hjiang/jsonxx#50]
Hi!

How can I parse values automatically? I use something like this:

```cpp
 json.has<jsonxx::Object>("data");
```

**But key ```data``` can have a value: Object, Array, Number, Boolean or String!?
So, is there a wildcard directive or something?**

For example:

```cpp
 json.has<boost::any>("data");
```

**Comment by hjiang** [comment]
You have to store the value somewhere when you read it, and C++ is a static language, so you have to know the type of the value.
