### ISSUE TITLE
Test case failing

### ISSUE THREAD

**Issue by meprem** [hjiang/jsonxx#54]
Hi,

Following test case is failing. Was it working before?

Regards,
Prem

    $:~/Code/jsonxx-master$ cat Makefile 
	CXXFLAGS=-W -Wall -g

	jsonxx_test: jsonxx_test.cc jsonxx.o

	jsonxx.o: jsonxx.h jsonxx.cc

	test: jsonxx_test
		./jsonxx_test

	.PHONY: clean
	clean:
		rm -f jsonxx_test *.o *~
	$:~/Code/jsonxx-master$ make
	g++ -W -Wall -g   -c -o jsonxx.o jsonxx.cc
	g++ -W -Wall -g    jsonxx_test.cc jsonxx.o   -o jsonxx_test
	jsonxx_test.cc: In function 'int main(int, const char**)':
	jsonxx_test.cc:563:24: warning: passing NULL to non-pointer argument 1 of 'jsonxx::Object& jsonxx::Object::operator<<(const T&) [with T = long int]' [-Wconversion-null]
	jsonxx_test.cc:563:24: warning: passing NULL to non-pointer argument 1 of 'jsonxx::Object& jsonxx::Object::operator<<(const T&) [with T = long int]' [-Wconversion-null]
	$:~/Code/jsonxx-master$ ls
	LICENSE   README.textile  jsonxx.h  jsonxx_test
	Makefile  jsonxx.cc       jsonxx.o  jsonxx_test.cc
	$:~/Code/jsonxx-master$ ./jsonxx_test 
	[JSONXX] expression 'value == "\b\f\n\r\t\xe\x2"' failed at jsonxx_test.cc:100 -> jsonxx_test: jsonxx.cc:29: void jsonxx::assertion(const char*, int, const char*, bool): Assertion `0' failed.
	Aborted
	$:~/Code/jsonxx-master$ gcc -v
	Using built-in specs.
	COLLECT_GCC=gcc
	COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.6/lto-wrapper
	Target: x86_64-linux-gnu
	Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
	Thread model: posix
	gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)

**Comment by hjiang** [comment]
Looks like it's been failing since ee691fbf2b445e77ceab4f0a787e569c7bbe9c01

I am not family with unicode, so if @gcamp or @r-lyeh could take a look, it would be great.

**Comment by meprem** [comment]
Ok..Got it.
To reflect dec to hex, the test case should also change from  
string teststr("\"\\b\\f\\n\\r\\t\\u0014\\u0002\"");
to 
string teststr("\"\\b\\f\\n\\r\\t\\u000e\\u0002\"");        

I will send a pull request.Thanks.
