### ISSUE TITLE
Create a Release

### ISSUE THREAD

**Issue by MatthewScholefield** [hjiang/jsonxx#63]
I was wondering if you guys could publish a release (perhaps version `0.1.0` or something). This would make it easier to use with meson, since I would be able to link to the source tarballs to download automatically in my code.

**Comment by AMDmi3** [comment]
The projects also already packaged in [some repositories](https://repology.org/project/jsonxx/versions) and I plan to package it for FreeBSD to use instead of bundled version in bonzomatic, and having official versioned releases would make is much easier to track updates and vulnerabilities.

**Comment by hjiang** [comment]
I've created a v1.0.0 release. I'm trying to pick up maintaining the project and work on existing open issues. All bug fixes will be in v1.x.
